// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ScalableMLModelOnWebAPIML.Model
{
    public class ModelInput
    {
        [ColumnName("descripcion"), LoadColumn(0)]
        public string Descripcion { get; set; }


        [ColumnName("violencia"), LoadColumn(1)]
        public float Violencia { get; set; }


    }
}
